[package]
name = "p2p-file-sharing"
version = "0.1.0"
authors = ["Zhukov"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

# serde_json is just for the example, not required in general
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
ipconfig = "0.2"

[target.'cfg(unix)'.dependencies]
machine-ip = "0.2"
