[package]
name = "p2p-file-sharing"
version = "0.1.0"
authors = ["User <user@company.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
